#!/usr/bin/env python3
import sys
import os
import argparse
import json
import hashlib

import requests

# Disable SSL warnings
# https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
import urllib3
urllib3.disable_warnings()

DATA_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'data')

def hash_of_remote_file(url, filename, user_agent, verify_ssl):
    headers = {'user-agent': user_agent}

    full_url = '{}/{}'.format(url, filename)

    try:
        sys.stdout.write("GET {} \t".format(full_url))
        if verify_ssl:
            r = requests.get(full_url, headers=headers)
        else:
            r = requests.get(full_url, headers=headers, verify=False)
        sys.stdout.write('{}\n'.format(r.status_code))

        if r.status_code == 200:
            h = hashlib.sha256(r.content).hexdigest()
            print("  SHA256 of {}: {}".format(filename, h))
            return h
        else:
            return None

    except Exception as e:
        print()
        print("{}".format(e))
        sys.exit(1)

def fingerprint(webapp, url, user_agent, verify_ssl):
    print("[] Fingerprinting version of {} at {}".format(webapp, url))

    # Load the data
    versions = json.load(open(os.path.join(DATA_DIR, '{}_versions.json'.format(webapp)), 'r'))
    data = json.load(open(os.path.join(DATA_DIR, '{}_data.json'.format(webapp)), 'r'))
    freq = json.load(open(os.path.join(DATA_DIR, '{}_freq.json'.format(webapp)), 'r'))

    # Keep track of the list of possible versions
    possible_versions = versions

    # Start with the most frequently modified files
    for filename in freq:
        # Get the hash of the remote file
        h = hash_of_remote_file(url, filename, user_agent, verify_ssl)
        if h == None:
            continue

        # Is the hash in the data?
        if h in data[filename]:
            # Rule out versions
            versions_to_delete = []
            for v in possible_versions:
                if v not in data[filename][h]:
                    versions_to_delete.append(v)
            for v in versions_to_delete:
                possible_versions.remove(v)
            print("  Possible versions: {}".format(possible_versions))

            if len(possible_versions) == 1:
                sys.exit(0)

        else:
            print('  Hash not in data, skipping')

def main():
    # Parse arguments
    parser = argparse.ArgumentParser()
    parser.add_argument('webapp', metavar='webapp', type=str, nargs=1, help="web app software being targeted (e.g. 'owncloud')")
    parser.add_argument('url', metavar='url', type=str, nargs=1, help='URL of the web app')
    parser.add_argument('--user-agent', metavar='user_agent', default="Mozilla/5.0 (Windows NT 6.1; rv:45.0) Gecko/20100101 Firefox/45.0", help='user agent string (default is Firefox in Windows)')
    parser.add_argument('--no-verify-ssl', const='no_verify_ssl', action='store_const', default=False, help="don't verify SSL certificate")
    args = parser.parse_args()

    # Validate args
    webapp = args.webapp[0]
    valid_webapps = ['owncloud', 'wordpress']
    if webapp not in valid_webapps:
        print("you must use one of the supported webapps: {}".format(valid_webapps))
        sys.exit(1)

    url = args.url[0]
    if not url.startswith('http://') and not url.startswith('https://'):
        print('url must start with http:// or https://')
        sys.exit(1)

    # Remove the trailing slash from the URL, if it's there
    url = url.rstrip('/')

    # Should we verify SSL certs?
    verify_ssl = (args.no_verify_ssl == False)

    # Start
    fingerprint(webapp, url, args.user_agent, verify_ssl)

if __name__ == '__main__':
    main()
